import { v4 as uuid } from "uuid";
import {
  product1,
  product10,
  product11,
  product12,
  product13,
  product2,
  product3,
  product4,
  product5,
  product6,
  product7,
  product8,
  product9,
} from "../../assets";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    name: "POLLY DOTS",
    img: product10,
    price: "2500",
    categoryName: "Women",
    rating: "3",
  },
  {
    _id: uuid(),
    name: "LEOTUDE",
    img: product1,
    price: "5000",
    categoryName: "Men",
    rating: "5",
  },
  {
    _id: uuid(),
    name: "TOONYPORT",
    img: product12,
    price: "2500",
    categoryName: "Kids",
    rating: "4",
  },
  {
    _id: uuid(),
    name: "VOXATI",
    img: product2,
    price: "1000",
    categoryName: "Men",
    rating: "2",
  },
  {
    _id: uuid(),
    name: "MONTREZ",
    img: product3,
    price: "2500",
    categoryName: "Men",
    rating: "4",
  },
  {
    _id: uuid(),
    name: "CASUAL",
    img: product4,
    price: "1299",
    categoryName: "Men",
    rating: "3",
  },
  {
    _id: uuid(),
    name: "FORMAL",
    img: product5,
    price: "1999",
    categoryName: "Men",
    rating: "4",
  },
  {
    _id: uuid(),
    name: "GENERIC",
    img: product6,
    price: "1199",
    categoryName: "Men",
    rating: "2",
  },
  {
    _id: uuid(),
    name: "GREEN TOP",
    img: product7,
    price: "2699",
    categoryName: "Women",
    rating: "5",
  },
  {
    _id: uuid(),
    name: "FLORAL",
    img: product8,
    price: "3599",
    categoryName: "Women",
    rating: "2",
  },
  {
    _id: uuid(),
    name: "TOP YELLOW",
    img: product9,
    price: "4599",
    categoryName: "Women",
    rating: "4",
  },
  {
    _id: uuid(),
    name: "ARIEL",
    img: product13,
    price: "3100",
    categoryName: "Kids",
    rating: "5",
  },
  {
    _id: uuid(),
    name: "BOLD ELEGANT",
    img: product11,
    price: "1200",
    categoryName: "Kids",
    rating: "2",
  },
  {
    _id: uuid(),
    name: "FARETO",
    img: product13,
    price: "3100",
    categoryName: "Kids",
    rating: "5",
  },
];
